### ISSUE TITLE
Overriding default nested values

### ISSUE THREAD

**Issue by voz** [yargs/yargs-parser#121] opened 2018-05-07 07:57 UTC
Hi there! Thanks for the awesome lib!

I'm trying to use nested fields in the default config to structure it better. But it seems that when I try to override one of the nested fields, it overrides the whole nested object.

Is it expected or am I doing something wrong?

Here is an example:

```js
const defaultConfig = {
  topField1: {
    nestedField1: 'hello',
    nestedField2: 'world'
  },
  topField2: 'great'
}

console.log('Default config: ', defaultConfig)

const yargsParser = require('yargs-parser')
const configAfterYargs = yargsParser(process.argv.slice(2), {
  default: defaultConfig
})

console.log('After yargs: ', configAfterYargs)
```

```bash
$ node yargs-nested-example.js --topField2 cool --topField1.nestedField2 planet
Default config:  { topField1: { nestedField1: 'hello', nestedField2: 'world' },
  topField2: 'great' }
After yargs:  { _: [],
  topField2: 'cool',
  topField1: { nestedField2: 'planet' } }
```

Now, `topField1.nestedField1` has disappeared.

**Comment by bcoe** [comment] 2019-01-28 04:56
@voz thank you for the kind words. see https://github.com/yargs/yargs/issues/1230, we're finally starting to take this work on.

**Comment by bcoe** [comment] 2019-01-28 04:57
I'm going to close this as a duplicate of the issue shared above, please feel free to join the conversation on that feature.

**Closed by bcoe** 2019-01-28 04:57 UTC
Labels: triaged
