### ISSUE TITLE
Bug: different result for -x1 and -1x when -x and -1 are both booleans

### ISSUE THREAD

**Issue by b1f6c1c4** [yargs/yargs-parser#283] opened 2020-06-11 00:11 UTC
```js
> require('yargs-parser')(['-x1'], { boolean: ['x', '1'] })
{ _: [], x: false }
> require('yargs-parser')(['-1x'], { boolean: ['x', '1'] })
{ '1': true, _: [], x: true }
```
What I'm looking for is to both get `{ '1': true, _: [], x: true }`, because `-x` and `-1` are both boolean switches and `1` is NOT just an argument for `-x`.

**Comment by QmarkC** [comment] 2020-06-11 03:14
Quick triage, looks like the issue is in [L270-L276](https://github.com/yargs/yargs-parser/blob/master/index.js#L270-L276):

```js
        // current letter is an alphabetic character and next value is a number
        if (/[A-Za-z]/.test(letters[j]) &&
          /^-?\d+(\.\d*)?(e-?\d+)?$/.test(next)) {
          setArg(letters[j], next)
          broken = true
          break
        }
```

Adding a check to see if next is a boolean alias seems to fix it and doesn't break any existing tests.

```js
        // current letter is an alphabetic character and next value is a number
        if (/[A-Za-z]/.test(letters[j]) &&
          /^-?\d+(\.\d*)?(e-?\d+)?$/.test(next) &&
          checkAllAliases(next, flags.bools) === false) {
          setArg(letters[j], next)
          broken = true
          break
        }
```

```js
const parse1 = parser(['-x1'], { boolean: ['x', '1'] })
console.log(parse1)
// { '1': true, _: [], x: true }

const parse2 = parser(['-1x'], { boolean: ['x', '1'] })
console.log(parse2)
// { '1': true, _: [], x: true }
```

**Comment by b1f6c1c4** [comment] 2020-06-12 18:49
@QmarkC This solution seems good and could you please make a PR?

**Comment by QmarkC** [comment] 2020-06-12 20:50
> @QmarkC This solution seems good and could you please make a PR?

@b1f6c1c4 I can look into this further after the TypeScript refactor #285 is merged.

**Comment by b1f6c1c4** [comment] 2020-07-19 01:51
@QmarkC Hi, could you please have a look at this?

**Closed** 2020-08-05 04:04 UTC
